fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  resetting:
    retry_ttl: 86400
  ## To solve the problem
  from_email:
    address: 'fenohasina@fenohasina.com'
    sender_name: "schoolAdmin"